# Generated by Django 3.2.5 on 2021-07-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='purchase',
            new_name='recipe',
        ),
    ]
