# Generated by Django 3.2.5 on 2021-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210710_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default=None, related_name='ingredients', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
